services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      MYSQL_DB_DATABASE: ${MYSQL_DB_DATABASE}
      MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    depends_on:
      mysql_golang:
        condition: service_healthy
    networks:
      - mysql
  mysql_golang:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
      MYSQL_USER: ${MYSQL_DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    ports:
      - "${MYSQL_DB_PORT}:3306"
    volumes:
      - mysql_volume_golang:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_DB_HOST}", "-u", "${MYSQL_DB_USERNAME}", "--password=${MYSQL_DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s 
    networks:
      - mysql

volumes:
  mysql_volume_golang:
networks:
  mysql:
