name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.4'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: |
          docker build -t golang-backend .

      # - name: Run tests
      #   run: |
      #     docker run --rm golang-backend go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: VPS_USER

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          # Install rsync and ssh client
          sudo apt-get update && sudo apt-get install -y rsync openssh-client

          # Setup SSH key
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Ensure the deployment directory exists on the VPS
          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "mkdir -p /home/ubuntu/deployment"

          # Sync files using rsync, excluding the .git directory
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude='.git' ./ $VPS_USER@$VPS_HOST:/home/ubuntu/deployment/

          # Run docker-compose on the VPS
          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd /home/ubuntu/deployment && docker-compose up -d"
